### PR TITLE
updated version, and changed source to gitHub, rather than pypi

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
since I changed the source to gitHub, might as well have someone review.

Also -- we don't have cell_tree2d as a dependency, because it's an optional dependency -- but should we ??

### CODE REVIEW

**Comment by ocefpaf** [comment]
> Also -- we don't have cell_tree2d as a dependency, because it's an optional dependency -- but should we ??

Optional dependencies in `conda-forge` are up to the maintainers. I am :+1:, so if you want go ahead and add it here.

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA I missed this one but feel free to merge it next time. The only :-1: here is the addition of the optional dependency `cell_tree2d`. We should leave `pyugrid` light for users who want just the basic functionality without compiled code.

**Comment by ChrisBarker-NOAA** [comment]
@ChrisBarker-NOAA https://github.com/ChrisBarker-NOAA I missed this one
but feel free to merge it next time. The only 👎 here is the addition of
the optional dependency cell_tree2d. We should leave pyugrid light for
users who want just the basic functionality without compiled code.

Well, that's why it's an optional dependency.

But as conda-forge can assure that there are  packages available, setting
it as a dependency in the conda-forge package means anyone that needs it,
gets it. And it won't break anyone's install.

And cell-tree2d is pretty lightweight as conda packages go :-)

No if I could just get MPL to stop downloading QT!

CHB

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/conda-forge/pyugrid-feedstock/pull/3#issuecomment-256296144,
or mute the thread

**Comment by ocefpaf** [comment]
> And cell-tree2d is pretty lightweight as conda packages go :-)

It is compiled code and breaks my pyugrid parser machine running on my raspberry pi. As you said it is optional, so let's keep it that way. It is easy enough to specify that in a `environment.yaml` file.

> No if I could just get MPL to stop downloading QT!

That will happen at some point BTW. We are planning this for a long time now.

**Comment by ChrisBarker-NOAA** [comment]
> It is compiled code and breaks my pyugrid parser machine running on my raspberry pi. As you said it is optional, so let's keep it that way.

are you loading pyugrid from a conda-forge package? if so -- why isn't cell_tree2D available? Though on a pi, you'll want things to b as lightweight as possible, yes.

On July27, you suggested I add it :-)

But really we need a better way to handle optional dependencies in conda (and piip). It's an ugly problem though -- not sure how to go about it.

>  It is easy enough to specify that in a environment.yaml file.

or a requirements.txt file -- in pip, they kinda-sort make the distinction between package dependencies and project dependencies. If we push the use of project dependencies, that may handle many of the optional dependecy issues. For this example:

cell_tree2D is not listed as a dependency of pyugrid.

If someone has a project that uses the parts of pyugrid that require cell_tree2D, then s/he puts both in their project dependencies file (requirements.txt or environment.yaml)

This is a cultural change, not a tooling change -- so both harder an easier :-)

meta-packages that can also help.

So we're good.

-CHB

**Pull request closed without merging**
