### PR TITLE
Add myself to the maintainers

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
I'm one of the major contributors to the package :-)

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
Wow! that was fast! 

-Thanks

**Comment by ocefpaf** [comment]
No need to wait for the CIs here. BTW, you can commit changes like this one with a `[skip ci]` message to prevent them from starting.

**Comment by ChrisBarker-NOAA** [comment]
great -- I was wondering about that -- seemed a waste to test building with a change like this.

**Comment by ChrisBarker-NOAA** [comment]
I don't seem to have push access to this repo -- should I? or does it take a while to to get set up?

**Comment by ocefpaf** [comment]
> I don't seem to have push access to this repo -- should I? or does it take a while to to get set up?

Our bots work tirelessly and (most of the time) they never fail :wink: 

But it may take a while until everything is processed.

**Pull request merged**
