### PR TITLE
version 0.3.1

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
Update Version

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
Hmm -- Appveyer failed in a Jupyter core problem -- why would Jupyter be involved at all here???

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Humn... This PR is not from a fork. Package will be uploaded before merging :unamused:

**Comment by ChrisBarker-NOAA** [comment]
OK, looks like all the builds are up on Anaconda.org now.

so, despite having gone through the wrong process -- any reason not to merge this now?

**Comment by ChrisBarker-NOAA** [comment]
thanks for cleaning this up!

**Pull request closed without merging**
